language: generic

services:
  - docker

before_install:
  - docker build -t shoutzor .
  - docker run -p 80:80 -p 8000:8000 shoutzor /bin/sh -c "cd /usr/share/nginx/html/tests/ && phpunit"
  - docker tag shoutzor xorinzor/shoutz0r:latest

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
